<?php

namespace AppBundle\Repository;

/**
 * ArrivalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByOrderDate(\DateTime $date)
    {
        $start = (new \DateTime($date->format('Y-m-d') . '00:00:00'));
        $end = (new \DateTime($date->format('Y-m-d') . '23:59:59'));

        $qb = $this->getQueryBuilder('e');

        $qb = $qb->andWhere('e.orderdate between :start and :end')
        ->setParameter('start', $start)
        ->setParameter('end', $end);

        return $qb->getQuery()->getResult();
    }
}
