<?php

namespace AppBundle\Repository;

/**
 * ArrivalOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
