<?php

namespace AppBundle\Repository;

/**
 * ArrivalOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArrivalOrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
