<?php

namespace AppBundle\Repository;

/**
 * KidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KidRepository extends \Doctrine\ORM\EntityRepository
{
}
